HEADERS += \
    $$PWD/Mqtt/CMqttTopic.h \
    $$PWD/Mqtt/Topics/Bus/usbchargetopic.h \
    $$PWD/Mqtt/Topics/CEmergencyAlertTopic.h \
    $$PWD/Mqtt/Topics/CGrConnectionTopic.h \
    $$PWD/Mqtt/Topics/CGrGuiTopic.h \
    $$PWD/Mqtt/Topics/CGrIncarnetInspectorTopic.h \
    $$PWD/Mqtt/Topics/CGrInformatorTopic.h \
    $$PWD/Mqtt/Topics/CGrLedTopic.h \
    $$PWD/Mqtt/Topics/CGrLiazTopic.h \
    $$PWD/Mqtt/Topics/CGrNavigationTopic.h \
    $$PWD/Mqtt/Topics/CGrOnvifTopic.h \
    $$PWD/Mqtt/Topics/CGrRecorderTopic.h \
    $$PWD/Mqtt/Topics/CGrSettingsTopic.h \
    $$PWD/Mqtt/Topics/CGrStmTopic.h \
    $$PWD/Mqtt/Topics/CGrValidatorsTopic.h \
    $$PWD/Mqtt/Topics/Gui/CGuiCvsStateTopic.h \
    $$PWD/Mqtt/Topics/Gui/CGuiShowCvsTopic.h \
    $$PWD/Mqtt/Topics/CSimpleTopic.h \
    $$PWD/Mqtt/Topics/CSystemTopic.h \
    $$PWD/Mqtt/Topics/Connection/CConnectionConnectionStateTopic.h \
    $$PWD/Mqtt/Topics/Connection/CConnectionVoiceDialCmdTopic.h \
    $$PWD/Mqtt/Topics/Connection/CConnectionVoiceDialState.h \
    $$PWD/Mqtt/Topics/Gui/CGuiSosTopic.h \
    $$PWD/Mqtt/Topics/IncarnetInspector/CIncarnetInspectorDeviceStateTopic.h \
    $$PWD/Mqtt/Topics/IncarnetInspector/CIncarnetInspectorStateTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorCmdToChangeMode.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorLcdTextTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorPlayDoorsTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorPlayStationTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorRouteStateTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorRoutesListTopic.h \
    $$PWD/Mqtt/Topics/Informator/CInformatorSelectedRouteTopic.h \
    $$PWD/Mqtt/Topics/Informator/InformatorDefines.h \
    $$PWD/Mqtt/Topics/Informator/RouteNetworkStructures.h \
    $$PWD/Mqtt/Topics/Informator/RoutesParser.h \
    $$PWD/Mqtt/Topics/Integration/CIntegrationPassangerCounterByStationTopic.h \
    $$PWD/Mqtt/Topics/Integration/CIntegrationPassangerCounterDetailedTopic.h \
    $$PWD/Mqtt/Topics/Led/CLedLoadFontStatusTopic.h \
    $$PWD/Mqtt/Topics/Led/CLedLoadFontTopic.h \
    $$PWD/Mqtt/Topics/Led/CLedSettingsAndRouteInfoTopic.h \
    $$PWD/Mqtt/Topics/Led/CLedTestTopic.h \
    $$PWD/Mqtt/Topics/Led/TextRcHandlers.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazAmbientTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazApparelTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazAutoinformerTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazBoardVoltageTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazCoolantTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazDisabledPersonReqTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorClosingTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorOpeningTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelPrimaryTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelSecondaryTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelPrimaryLitersTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelSecondaryLitersTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazInsideTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazKamazErrorTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazKneelingTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazMotorTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazOilTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazPassangerRequestTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazSalonTempTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazSosButtonTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazTahospeedTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazTransmissionForwardTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazTransmissionReverseTopic.h \
    $$PWD/Mqtt/Topics/Liaz/CLiazVehStateTopic.h \
    $$PWD/Mqtt/Topics/Navigation/CNavigationGnssStateTopic.h \
    $$PWD/Mqtt/Topics/Navigation/CNavigationRawNmeaTopic.h \
    $$PWD/Mqtt/Topics/Onvif/COnvifFoundCamerasTopic.h \
    $$PWD/Mqtt/Topics/Recorder/CRecorderCamerasTopic.h \
    $$PWD/Mqtt/Topics/Stm/CGrStmRoTopic.h \
    $$PWD/Mqtt/Topics/Stm/CStmRwTopic.h \
#    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLed1Topic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoBatVoltageTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoButtonTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoIgnTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoMfiTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoOneWireTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoTamperTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwTangdestTopic.h \
    $$PWD/Mqtt/Topics/Stm/CStmIfcTopic.h \
    $$PWD/Mqtt/Topics/Stm/CStmUpdateFwTopic.h \
    $$PWD/Mqtt/Topics/Stm/CStmHwResetTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcCanRxTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcCanTxTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs232RxTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs232TxTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs485RxTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs485TxTopic.h \
#    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwBatteryTimeTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwGnssTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLedTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLteTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwOutTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/Lte/CStmRwLtePowerTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/Gnss/CStmRwGnssPowerTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/Gnss/CStmRwGnssBackupTopic.h \
    $$PWD/Mqtt/Topics/Stm/Rw/Lte/CStmRwLteSimNumberTopic.h \
    $$PWD/Mqtt/Topics/Settings/CSettingsSettingChangeTopic.h \
    $$PWD/Mqtt/Topics/System/CGrSystemHealthTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CGrSystemHealthHddStatusTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddPrepareTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusVolumePartitionTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusVolumeTopic.h \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthTemperatureTopic.h \
    $$PWD/Mqtt/Topics/Validators/CTaganrogTerminalCommandTopic.h \
    $$PWD/Mqtt/Topics/Validators/CTaganrogTerminalStatus.h \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterByStationTopic.h \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterDetailedTopic.h \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterOnStationTopic.h \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterTopic.h \
    $$PWD/Mqtt/Topics/Validators/CValidatorsStateTopic.h \
    $$PWD/Mqtt/Topics/CAudioTopic.h \
    $$PWD/Mqtt/Topics/Audio/CAudioTangDestTopic.h \
    $$PWD/Mqtt/Topics/Audio/CAudioTrackToTopic.h \
    $$PWD/Mqtt/Topics/Audio/CAudioVolumeTopic.h \
    $$PWD/Mqtt/Topics/Audio/CAudioMuteTopic.h \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteDriverTopic.h \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteSalonTopic.h \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteSpeakingCityTopic.h \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioDriverVolumeTopic.h \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioSalonVolumeTopic.h \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioSpeakingCityVolumeTopic.h \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioMicVolumeTopic.h \
    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToStatusTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToDriverTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToSalonTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToSpeakingCityTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToSpeakingCityStatusTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToDriverStatusTopic.h \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToSalonStatusTopic.h \
    $$PWD/Mqtt/Topics/System/CSystemFactoryTesting.h \
    $$PWD/Mqtt/Topics/System/CSystemConfigurationTopic.h \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationCanTopic.h \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationMfiTopic.h \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationRepoTopic.h \
    $$PWD/Mqtt/Topics/Bus/CBusDoorTopic.h \
    $$PWD/Mqtt/Topics/CGrIntegrationTopic.h \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoBoardVoltageTopic.h \
    $$PWD/Mqtt/Topics/Simulator/CMotionSimulatorTopic.h

SOURCES += \
    $$PWD/Mqtt/CMqttTopic.cpp \
    $$PWD/Mqtt/Topics/Bus/usbchargetopic.cpp \
    $$PWD/Mqtt/Topics/CEmergencyAlertTopic.cpp \
    $$PWD/Mqtt/Topics/CGrConnectionTopic.cpp \
    $$PWD/Mqtt/Topics/CGrGuiTopic.cpp \
    $$PWD/Mqtt/Topics/CGrIncarnetInspectorTopic.cpp \
    $$PWD/Mqtt/Topics/CGrInformatorTopic.cpp \
    $$PWD/Mqtt/Topics/CGrLedTopic.cpp \
    $$PWD/Mqtt/Topics/CGrLiazTopic.cpp \
    $$PWD/Mqtt/Topics/CGrNavigationTopic.cpp \
    $$PWD/Mqtt/Topics/CGrOnvifTopic.cpp \
    $$PWD/Mqtt/Topics/CGrRecorderTopic.cpp \
    $$PWD/Mqtt/Topics/CGrSettingsTopic.cpp \
    $$PWD/Mqtt/Topics/CGrStmTopic.cpp \
    $$PWD/Mqtt/Topics/CGrValidatorsTopic.cpp \
    $$PWD/Mqtt/Topics/Gui/CGuiCvsStateTopic.cpp \
    $$PWD/Mqtt/Topics/Gui/CGuiShowCvsTopic.cpp \
    $$PWD/Mqtt/Topics/CSystemTopic.cpp \
    $$PWD/Mqtt/Topics/Connection/CConnectionConnectionStateTopic.cpp \
    $$PWD/Mqtt/Topics/Connection/CConnectionVoiceDialCmdTopic.cpp \
    $$PWD/Mqtt/Topics/Connection/CConnectionVoiceDialState.cpp \
    $$PWD/Mqtt/Topics/Gui/CGuiSosTopic.cpp \
    $$PWD/Mqtt/Topics/IncarnetInspector/CIncarnetInspectorDeviceStateTopic.cpp \
    $$PWD/Mqtt/Topics/IncarnetInspector/CIncarnetInspectorStateTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorCmdToChangeMode.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorLcdTextTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorPlayDoorsTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorPlayStationTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorRouteStateTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorRoutesListTopic.cpp \
    $$PWD/Mqtt/Topics/Informator/CInformatorSelectedRouteTopic.cpp \
    $$PWD/Mqtt/Topics/Integration/CIntegrationPassangerCounterByStationTopic.cpp \
    $$PWD/Mqtt/Topics/Integration/CIntegrationPassangerCounterDetailedTopic.cpp \
    $$PWD/Mqtt/Topics/Led/CLedLoadFontStatusTopic.cpp \
    $$PWD/Mqtt/Topics/Led/CLedLoadFontTopic.cpp \
    $$PWD/Mqtt/Topics/Led/CLedSettingsAndRouteInfoTopic.cpp \
    $$PWD/Mqtt/Topics/Led/CLedTestTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazAmbientTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazApparelTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazAutoinformerTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazBoardVoltageTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazCoolantTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazDisabledPersonReqTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorClosingTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorOpeningTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazDoorTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelPrimaryTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelSecondaryTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelPrimaryLitersTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazFuelLevelSecondaryLitersTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazInsideTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazKamazErrorTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazKneelingTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazMotorTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazOilTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazPassangerRequestTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazSalonTempTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazSosButtonTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazTahospeedTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazTransmissionForwardTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazTransmissionReverseTopic.cpp \
    $$PWD/Mqtt/Topics/Liaz/CLiazVehStateTopic.cpp \
    $$PWD/Mqtt/Topics/Navigation/CNavigationGnssStateTopic.cpp \
    $$PWD/Mqtt/Topics/Navigation/CNavigationRawNmeaTopic.cpp \
    $$PWD/Mqtt/Topics/Onvif/COnvifFoundCamerasTopic.cpp \
    $$PWD/Mqtt/Topics/Recorder/CRecorderCamerasTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/CGrStmRoTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/CStmRwTopic.cpp \
#    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLed1Topic.cpp \
    $$PWD/Mqtt/Topics/Stm/CStmIfcTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/CStmUpdateFwTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/CStmHwResetTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcCanRxTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcCanTxTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs232RxTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs232TxTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs485RxTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ifc/CStmIfcRs485TxTopic.cpp \
#    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwBatteryTimeTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoBatVoltageTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoButtonTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoIgnTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoMfiTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoOneWireTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoTamperTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwGnssTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLedTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwLteTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwOutTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/CStmRwTangdestTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/Gnss/CStmRwGnssBackupTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/Gnss/CStmRwGnssPowerTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/Lte/CStmRwLtePowerTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Rw/Lte/CStmRwLteSimNumberTopic.cpp \
    $$PWD/Mqtt/Topics/Settings/CSettingsSettingChangeTopic.cpp \
    $$PWD/Mqtt/Topics/System/CGrSystemHealthTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CGrSystemHealthHddStatusTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddPrepareTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusVolumePartitionTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthHddStatusVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/System/Health/CSystemHealthTemperatureTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CTaganrogTerminalCommandTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CTaganrogTerminalStatus.cpp \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterByStationTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterDetailedTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterOnStationTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CValidatorsPassangerCounterTopic.cpp \
    $$PWD/Mqtt/Topics/Validators/CValidatorsStateTopic.cpp \
    $$PWD/Mqtt/Topics/CAudioTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/CAudioTangDestTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/CAudioTrackToTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/CAudioVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/CAudioMuteTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioMicVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioSpeakingCityVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioSalonVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Volume/CAudioDriverVolumeTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteSpeakingCityTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteSalonTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/Mute/CAudioMuteDriverTopic.cpp \
    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToStatusTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToSpeakingCityTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToSalonTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/CAudioTrackToDriverTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToDriverStatusTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToSalonStatusTopic.cpp \
#    $$PWD/Mqtt/Topics/Audio/TrackTo/Status/CAudioTrackToSpeakingCityStatusTopic.cpp \
    $$PWD/Mqtt/Topics/System/CSystemFactoryTesting.cpp \
    $$PWD/Mqtt/Topics/System/CSystemConfigurationTopic.cpp \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationCanTopic.cpp \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationMfiTopic.cpp \
    $$PWD/Mqtt/Topics/System/Configuration/CSystemConfigurationRepoTopic.cpp \
    $$PWD/Mqtt/Topics/Bus/CBusDoorTopic.cpp \
    $$PWD/Mqtt/Topics/CGrIntegrationTopic.cpp \
    $$PWD/Mqtt/Topics/Stm/Ro/CStmRoBoardVoltageTopic.cpp \
    $$PWD/Mqtt/Topics/Simulator/CMotionSimulatorTopic.cpp



